# avoid conda-smithy picking up `- ruby` and thinking it needs to
# populate separate builds based on the multi-pin in the pinning.
ruby:
  - "*"
c_compiler:     # [win]
  - vs2022      # [win]
cxx_compiler:   # [win]
  - vs2022      # [win]