{% set name = "ruby" %}
{% set version = "2.6.3" %}
{% set major_minor = '.'.join(version.split('.')[0:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cache.ruby-lang.org/pub/ruby/{{ major_minor }}/ruby-{{ version }}.tar.gz
  sha256: 577fd3795f22b8d91c1d4e6733637b0394d4082db659fccf224c774a2b1c82fb

build:
  number: 0
  skip: True  # [win]
  track_features:
    - rb{{ version | replace(".", "") }}

requirements:
  build:
    - make
    - cmake
    - sed
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openssl
    - zlib
    - readline
    - tk
    - yaml
    - gettext  # [osx]
    - gmp
  run:
    - openssl
    - zlib
    - readline
    - tk
    - yaml
    - gettext  # [osx]
    - gmp

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  commands:
    - ruby --version
    - gem --version
    - ruby -e 'puts "Hi, from Ruby!"'
    - ruby -r rubygems -e 'puts "Has gems."; exit 0'
    - ruby -r openssl -r readline -r yaml -r zlib -e 'puts "Has all dependencies."; exit 0'
    # Tests it can build libraries with native dependencies
    - gem install hitimes

about:
  home: https://www.ruby-lang.org/
  license: GPL v2
  license_family: GPL
  license_file: COPYING
  summary: 'A dynamic, open source programming language with a focus on simplicity and productivity.'
  description: |
    A dynamic, open source programming language with a focus on simplicity and productivity.
    It has an elegant syntax that is natural to read and easy to write.
  doc_url: https://www.ruby-lang.org/en/documentation/
  dev_url: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/

extra:
  recipe-maintainers:
    - scopatz
    - jimmynguyc
