{% set name = "ruby" %}
{% set version = "3.2.2" %}
{% set major_minor = '.'.join(version.split('.')[0:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cache.ruby-lang.org/pub/ruby/{{ major_minor }}/ruby-{{ version }}.tar.gz
  sha256: 96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc
  patches:
    # Patches/work-arounds for passing make check
    - disable-backtrace-with-lines.patch
    - fix-isinf-redefinition-msvc.patch  # [win]
    - 0001-Dont-t-add-SDKROOT-to-vals.patch

build:
  number: 0
  track_features:
    - rb{{ major_minor | replace(".", "") }}
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    # We need CXX during build time to generate rbconfig.rb
    - libstdcxx-ng

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf    # [unix]
    - automake    # [unix]
    - make        # [unix]
    - pkg-config
    # We need all host deps also in build for cross-compiling
    - gettext     # [build_platform != target_platform]
    - gmp         # [build_platform != target_platform]
    - libffi      # [build_platform != target_platform]
    - ncurses     # [build_platform != target_platform]
    - openssl     # [build_platform != target_platform]
    - readline    # [build_platform != target_platform]
    - yaml        # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - gdbm        # [x86 and unix]
    - gettext     # [osx]
    - gmp         # [unix]
    - libffi
    - ncurses     # [unix]
    - openssl
    - readline    # [unix]
    - yaml        # [unix]
    - zlib
  run:
    - gettext     # [osx]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  files:
    - native/hello.c
    - native/config.rb
  commands:
    - ruby --version
    - gem --version
    - ruby -e 'puts "Hi, from Ruby!"'
    - ruby -r rubygems -e 'puts "Has gems."; exit 0'
    - ruby -r fiddle -r openssl -r yaml -r zlib -e 'puts "Has all dependencies."; exit 0'
    - ruby -r readline -e 'puts "Has readline."; exit 0'  # [unix]

    # Tests it can build libraries with native dependencies
    - cd native                        # [unix]
    - ruby config.rb                   # [unix]
    - make                             # [unix]
    - ruby -r ./hello.so -e 'hello'    # [unix]

about:
  home: https://www.ruby-lang.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: A dynamic, open source programming language with a focus on simplicity and productivity.
  description: |
    A dynamic, open source programming language with a focus on simplicity and productivity.
    It has an elegant syntax that is natural to read and easy to write.
  doc_url: https://www.ruby-lang.org/en/documentation/
  dev_url: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/

extra:
  recipe-maintainers:
    - scopatz
    - jimmynguyc
    - sodre
    - wolfv
    - xhochy
