context:
  name: ruby
  version: "4.0.3"
  major_minor: ${{ (version | split('.'))[0:2] | join('.') }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://cache.ruby-lang.org/pub/ruby/${{ major_minor }}/ruby-${{ version }}.tar.gz
  sha256: 77964acc370d5c8375b9502e5ba6c13c03ef91ab9eb9f521c84fb42b9c9a6b0f
  patches:
    - 0001-fix-rubygems-generate-plugins-nil.patch

build:
  number: 0

requirements:
  build:
    # ruby for bootstrapping itself
    - ruby
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - if: unix
      then:
        - autoconf
        - automake
        - make
    - pkg-config
  host:
    - if: x86 and unix
      then: gdbm
    - if: osx
      then: gettext
    - libffi
    - if: linux
      then: libxcrypt
    - if: unix
      then:
        - ncurses
        - readline
        - gmp
    - openssl
    - yaml
    - zlib
  run:
    - if: osx
      then: gettext
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      # We need CXX during build time to generate rbconfig.rb
      - ${{ compiler('cxx') }}

tests:
  - requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - if: unix
          then: make
    files:
      recipe:
        - native/hello.c
        - native/config.rb
    script:
      - ruby --version
      - gem --version
      - ruby -e 'puts "Hi, from Ruby!"'
      - ruby -r rubygems -e 'puts "Has gems."; exit 0'
      - ruby -r fiddle -r openssl -r yaml -r zlib -e 'puts "Has all dependencies."; exit 0'
      - if: unix
        then:
      # Tests it can build libraries with native dependencies
          - ruby -r readline -e 'puts "Has readline."; exit 0'
          - cd native
          - ruby config.rb
          - make
          - ruby -r ./hello.so -e 'hello'
about:
  homepage: https://www.ruby-lang.org/
  license: BSD-2-Clause
  license_file: COPYING
  summary: A dynamic, open source programming language with a focus on simplicity and productivity.
  description: |
    A dynamic, open source programming language with a focus on simplicity and productivity.
    It has an elegant syntax that is natural to read and easy to write.
  documentation: https://www.ruby-lang.org/en/documentation/
  repository: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/

extra:
  recipe-maintainers:
    - scopatz
    - jimmynguyc
    - sodre
    - wolfv
    - xhochy
