appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: travis}
travis:
  secure: {BINSTAR_TOKEN: JQ+G+j/4sdqR4JyCtrN2wiy5DGAp+j82JoNAtsHp655ropuFMgoZ5tKNl22feDj8W/+SdH0teNWhG076DN5DWQDyPn5zL6s1i1Vkamu9O2ee138PBC3PsonsoUb7O42zAcuIphKc+w0YyXTxc53vxZYbqIFsdV1lAu78c0FzP0WjAjrpQUWSCvqb3upJ1V8Cmnad7GFwVSjfopTGhu2MoMYhK13Qb78zHc8/Xlk6Mb8bzskOq1edArNv+RSFqQuXzUANxN48feADEnGfI11GX+Knm+WlVDXbPvgm/syWcxT72Vjl/VZd2p/Gp6TYj8r02esyj896ohjnf78A2UlM+UZYF7O9vgi1K6QeSpfCnMjA6dpCYfVvuVCZ1J90s0t7QwET687aWy5F9R4YzjkvApq/6IFIBmDYTJsJBVyyAVRws6fhG3V4Amw1xBgZR5oBq+teYiIxYYB33YLlTMWlU3ahKtw/bRns/vVYSgzOFRIigEh5LGLme9duOdcmQTDMSF6Xe2s9Zp6iHjdS47kXXjHitV7v4aIKKIttTQFGKf7l+jCAT2iZrT1p9O+YRet5teDOv1GteCru1M9Y9C6H8N/MGvYMZdjwgxhoG/Utb4ZQIuuAdfYvSPUDWz7UsZ5uzAPccycrs6Am7ea3HhPPp4yyBYtNFt7lbrFqL3CV8xs=}
conda_forge_output_validation: false
